### ISSUE TITLE
node_14.x bionic Release   Certificate verification failed

### ISSUE THREAD

**Issue by SilasK** [jupyterhub/mybinder.org-deploy#2041]
### Bug description

My r-container doesn't build anymore. due to problems with a node certificate. 

I already put a comment to the forum but  I cannot change the background of binderhub.
https://discourse.jupyter.org/t/node-14-x-bionic-release-does-not-have-a-release-file/11048/6

#### Expected behaviour

[This](https://mybinder.org/v2/gh/metagenome-atlas/BinderTutorial/R?urlpath=git-pull%3Frepo%3Dhttps%253A%252F%252Fgithub.com%252Fmetagenome-atlas%252FTutorial%26urlpath%3Drstudio%252F%26branch%3Dmaster) is my binder that I would like to build

#### Actual behaviour
Error as seen here https://discourse.jupyter.org/t/node-14-x-bionic-release-does-not-have-a-release-file/11048/6

### How to reproduce
Click on the link

### Your personal set up

 - OS: Max os mojave
 
 - Version(s): 10.14.6
 

I use mybinder. 

- <details><summary>Full environment</summary>

```
# paste output of `pip freeze` or `conda list` here
```
</details>

- <details><summary>Configuration</summary>

```python
# jupyterhub_config.py
```
</details>

- <details><summary>Logs</summary>

```
# paste relevant logs here, if any
```
</details>

**Comment by choldgraf** [comment]
It looks like this is a broader problem in general with node, it seems like the node folks are working on it so we should monitor that conversation as it evolves: https://github.com/nodesource/distributions/issues/1266#issuecomment-931448879

**Comment by meeseeksmachine** [comment]
This issue has been mentioned on **Jupyter Community Forum**. There might be relevant details there:

https://discourse.jupyter.org/t/node-14-x-bionic-release-does-not-have-a-release-file/11048/10

**Comment by Kirill888** [comment]
> It looks like this is a broader problem in general with node, it seems like the node folks are working on it so we should monitor that conversation as it evolves: [nodesource/distributions#1266 (comment)](https://github.com/nodesource/distributions/issues/1266#issuecomment-931448879)

Reading through comments it looks like updating base docker image with latest version of `ca-certificates` should fix it, but it's not something one can work around as user other than switching to Docker based binder.

**Comment by manics** [comment]
The behaviour is inconsistent across the mybinder.org federation

Testing with `https://<federation-member>/v2/gh/metagenome-atlas/BinderTutorial/R`:
- gesis works
- gke works
- ovh works
- turing fails

Note that the original URL https://mybinder.org/v2/gh/metagenome-atlas/BinderTutorial/R now works, presumably because I triggered a build on GKE, but it will still fail if you go direct to Turing.

**Comment by minrk** [comment]
Does that mean clearing the build cache on turing would fix it (i.e. restart dind pods)?

**Comment by yuvipanda** [comment]
What is the status of this now?

**Comment by meeseeksmachine** [comment]
This issue has been mentioned on **Jupyter Community Forum**. There might be relevant details there:

https://discourse.jupyter.org/t/node-14-x-bionic-release-does-not-have-a-release-file/11048/12

**Comment by manics** [comment]
I've just posted on Discourse as @meeseeksmachine has pointed out 😃.

**Comment by yuvipanda** [comment]
With https://github.com/jupyterhub/repo2docker/pull/847, we no longer use nodesource! So this is not a problem anymore.
